# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/google/go-containerregistry"
  # HEAD as of 2018-08-06
  revision = "5f7b0e4895413d785ff15b84d218d73e8a47866a"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.3"

[[override]]
  name = "github.com/json-iterator/go"
  # This is the commit at which k8s depends on this in 1.11
  # It seems to be broken at HEAD.
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]]
  name = "k8s.io/kubernetes"
  # TODO(mattmoor): Why does only a commit work?
  revision = "91e7b4fd31fcd3d5f436da26c980becec37ceefe"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "1ff28809256a84bb6966640ff3d0371af82ccba4"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "56a0b1d2af3b65d5f1f7a330e02faaf48b473c5a"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
